---
- name: cron restart
  service:
    name: cron
    state: restarted
  changed_when: false

- name: get cron pid
  command: systemctl show --property MainPID cron # noqa 303
  register: cron_pid
  changed_when: false

- name: search for errors
  shell: 'journalctl -u cron -t cron | grep "cron\[{{ cron_pid.stdout.split("=")[1] }}\]: Error"'
  register: cron_syntax_check
  failed_when: cron_syntax_check.stderr | length > 0
  ignore_errors: true
  changed_when: false

- name: show errors
  debug:
    msg: "{{ cron_syntax_check.stdout }}"
  when: cron_syntax_check.rc == 0

- name: Notify if bad syntax
  assert:
    that:
      - cron_syntax_check.rc != 0
    fail_msg: "Cron configuration check failed. You should check debug information above and fix the problem(s)."
